server:
  httpauth:
    enabled: false
    username: ""
    password: ""
  addr: :9000
  logOutfile:
  mode: product
  db_host: 
  db_port: 
  db_name: 
  db_user: 
  db_password: 
  conn_max_idle: 30
  connMaxConnection: 200
client:
  server_url: http://localhost:9000
